In [4]:
import pandas as pd

In [5]:
hospital_df = pd.read_csv("data/raw/hospitals.csv")
hospital_df

,name,type,opened,district,ownership,beds,staff
0,Changi General Hospital,Acute,1998,Simei,Public (SingHealth),1043.0,5736.0
1,KK Women's and Children's Hospital,Acute,1858,Rochor,Public (SingHealth),848.0,4861.0
2,Sengkang General Hospital,Acute,2018,Sengkang,Public (SingHealth),799.0,3797.0
3,Singapore General Hospital,Acute,1821,Outram,Public (SingHealth),1939.0,9201.0
4,Khoo Teck Puat Hospital,Acute,2010,Yishun,Public (National Healthcare Group),795.0,NaN
5,Tan Tock Seng Hospital,Acute,1844,Novena,Public (National Healthcare Group),1700.0,NaN
6,Woodlands Hospital,Acute,2023,Woodlands,Public (National Healthcare Group),1800.0,NaN
7,Alexandra Hospital,Acute,1938,Queenstown,Public (National University Health System),326.0,NaN
8,National University Hospital,Acute,1985,Kent Ridge,Public (National University Health System),1200.0,8271.0
9,Ng Teng Fong General Hospital,Acute,2015,Jurong East,Public (National University Health System),700.0,NaN
10,Mount Alvernia Hospital,Acute,1961,Marymount,Public (National University Health System),NaN,319.0
11,Crawfurd Hospital,Acute,2012,Bukit Timah,Not-for-Profit,NaN,31.0
12,Farrer Park Hospital,Acute,2016,Farrer Park,Private,NaN,121.0
13,Gleneagles Hospital,Acute,1957,Tanglin,Private (Parkway Pantai),257.0,NaN
14,Mount Elizabeth Hospital,Acute,1979,Orchard,Private (Parkway Pantai),345.0,NaN
15,Mount Elizabeth Novena Hospital,Acute,2012,Novena,Private (Parkway Pantai),333.0,NaN
16,Parkway East Hospital,Acute,1942,Joo Chiat,Private (Parkway Pantai),143.0,NaN
17,Raffles Hospital,Acute,2002,Bugis,Private (Parkway Pantai),NaN,380.0
18,Thomson Medical Centre,Acute,1979,Thomson,Private (Raffles Medical Group),NaN,187.0
19,Sengkang Community Hospital,Community,2018,Sengkang,NaN,400.0,407.0
20,Woodlands Hospital,Community,2023,Woodlands,Public (National Healthcare Group),NaN,NaN
21,Yishun Community Hospital,Community,2015,Yishun,Public (National Healthcare Group),224.0,NaN
22,Jurong Community Hospital,Community,2015,Jurong East,Public (National Healthcare Group),NaN,400.0
23,Ang Mo Kio - Thye Hua Kwan Hospital,Community,1993,Ang Mo Kio,Public (National University Health System),NaN,360.0
24,Ren Ci Community Hospital,Community,1994,Novena,Not-for-Profit,NaN,NaN
25,St. Andrew's Community Hospital,Community,1992,Simei,Not-for-Profit,NaN,277.0
26,St Luke's Hospital,Community,1996,Bukit Batok,Not-for-Profit,NaN,NaN
27,Institute of Mental Health,Psychiatric,1841,Hougang,NaN,NaN,2010.0

In [6]:
mrt_df = pd.read_csv("data/raw/mrt_stations.csv")
mrt_df

                  name  code  lines  opening_year  latitude  longitude
0            Admiralty  NS10     NS        1996.0       NaN        NaN
1             Aljunied   EW9     EW        1989.0       NaN        NaN
2           Ang Mo Kio  NS16  NS|CR        1987.0       NaN        NaN
3              Bartley  CC12     CC        2009.0       NaN        NaN
4             Bayfront   CE1  CC|DT        2012.0       NaN        NaN
..                 ...   ...    ...           ...       ...        ...
188          Brickland   NS3     NS        2034.0       NaN        NaN
189  Changi Terminal 5  TE32  TE|CR           NaN       NaN        NaN
190                DE1   DE1     DT        2035.0       NaN        NaN
191               JS2A   JS2     JR           NaN       NaN        NaN
192       Sungei Kadut   NS6  NS|DT        2035.0       NaN        NaN

[193 rows x 6 columns]

In [7]:
schools_df = pd.read_csv("data/raw/schools.csv")
schools_df

,name,type,education_tag,address,postal_code,phone,email,website,zone,school_active,is_enrolling,latitude,longitude
0,MOE Kindergarten @ Alexandra,preschool,MOE Kindergarten,2A Prince Charles Crescent,159016.0,6248 5400,mk_alexandra@moe.edu.sg,https://www.alexandrapri.moe.edu.sg/mk-at-alex...,Bukit Merah,True,True,NaN,NaN
1,MOE Kindergarten @ Anchor Green,preschool,MOE Kindergarten,31 Anchorvale Drive,544969.0,6886 1356,mk_anchorgreen@moe.edu.sg,https://anchorgreenpri.moe.edu.sg/mk-at-anchor...,Sengkang,True,True,NaN,NaN
2,MOE Kindergarten @ Ang Mo Kio,preschool,MOE Kindergarten,20 Ang Mo Kio Avenue 3,569920.0,6250 9029,mk_angmokio@moe.edu.sg,https://www.angmokiopri.moe.edu.sg/moe-kinderg...,Ang Mo Kio,True,True,NaN,NaN
3,MOE Kindergarten @ Angsana,preschool,MOE Kindergarten,51 Tampines Street 61,528565.0,6229 6455,mk_angsana@moe.edu.sg,https://www.angsanapri.moe.edu.sg/mk-at-angsan...,Tampines,True,True,NaN,NaN
4,MOE Kindergarten @ Bendemeer,preschool,MOE Kindergarten,91 Bendemeer Road,339948.0,6298 2911,mk_bendemeer@moe.edu.sg,https://www.bendemeerpri.moe.edu.sg/mk-at-bend...,Kallang,True,True,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,St. Joseph's Institution (Junior College),jc,Junior Colleges and Millennia Institute,Malcolm Road,308274.0,62500022,contact@sji.edu.sg,http://www.sji.edu.sg,NaN,NaN,NaN,NaN,NaN
407,Tampines Meridian Junior College,jc,Junior Colleges and Millennia Institute,Pasir Ris Street 71,518799.0,63493660,tmjc@moe.edu.sg,http://www.tmjc.moe.edu.sg,NaN,NaN,NaN,NaN,NaN
408,Temasek Junior College,jc,Junior Colleges and Millennia Institute,Tampines Avenue 9,529564.0,64428066,temasek_jc@moe.edu.sg,http://www.temasekjc.moe.edu.sg,NaN,NaN,NaN,NaN,NaN
409,Victoria Junior College,jc,Junior Colleges and Millennia Institute,Marine Vista,449035.0,64485011,victoria_jc@moe.edu.sg,https://www.victoriajc.moe.edu.sg/,NaN,NaN,NaN,NaN,NaN
410,Yishun Innova Junior College,jc,Junior Colleges and Millennia Institute,Yishun Ring Road,768675.0,62579873,yijc@moe.edu.sg,https://yijc.moe.edu.sg/,NaN,NaN,NaN,NaN,NaN